name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run format checker
        run: npm run format

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v3
        with:
          configFile: commitlint.config.cjs
